# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'cocoapods', '>= 1.7.0', '< 2.0'
gem 'cocoapods-virus', path: '/Users/xiongzenghui/Desktop/cocoapods-virus'